/* DLE Connect - Project Management & Engineering Schema
   Target: Microsoft SQL Server / DLE_Enterprise
   Design: schema-isolated, audit-ready, soft-delete, optimistic rowversion, UTC timestamps
*/
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name='pm') EXEC('CREATE SCHEMA pm');
GO
CREATE TABLE pm.Projects(
 ProjectId uniqueidentifier NOT NULL CONSTRAINT PK_pm_Projects PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 ProjectCode nvarchar(30) NOT NULL, ProjectName nvarchar(200) NOT NULL, ProjectType nvarchar(30) NOT NULL,
 ClientId uniqueidentifier NULL, ClientName nvarchar(200) NULL, BusinessUnit nvarchar(100) NOT NULL,
 ProjectManagerEmployeeId uniqueidentifier NULL, ExecutiveSponsorEmployeeId uniqueidentifier NULL,
 ContractNumber nvarchar(80) NULL, ContractValue decimal(19,4) NOT NULL DEFAULT 0, Currency char(3) NOT NULL DEFAULT 'NGN',
 CostCentre nvarchar(40) NULL, CommercialModel nvarchar(30) NULL, Location nvarchar(200) NULL,
 PlannedStart date NOT NULL, PlannedFinish date NOT NULL, ForecastFinish date NULL, ActualFinish date NULL,
 Phase nvarchar(50) NULL, Status nvarchar(30) NOT NULL DEFAULT 'Draft', Health nvarchar(20) NOT NULL DEFAULT 'Healthy',
 PlannedProgress decimal(7,3) NOT NULL DEFAULT 0, ActualProgress decimal(7,3) NOT NULL DEFAULT 0,
 SchedulePerformanceIndex decimal(8,4) NULL, CostPerformanceIndex decimal(8,4) NULL,
 Description nvarchar(max) NULL, SecurityClassification nvarchar(30) NOT NULL DEFAULT 'DLE Internal',
 CreatedBy uniqueidentifier NOT NULL, CreatedAt datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
 ModifiedBy uniqueidentifier NULL, ModifiedAt datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
 IsDeleted bit NOT NULL DEFAULT 0, RowVersion rowversion,
 CONSTRAINT UQ_pm_Projects_ProjectCode UNIQUE(ProjectCode),
 CONSTRAINT CK_pm_Projects_Dates CHECK(PlannedFinish>=PlannedStart),
 CONSTRAINT CK_pm_Projects_Progress CHECK(PlannedProgress between 0 and 100 AND ActualProgress between 0 and 100)
); GO
CREATE INDEX IX_pm_Projects_StatusHealth ON pm.Projects(Status,Health) INCLUDE(ProjectCode,ProjectName,ProjectManagerEmployeeId,PlannedFinish,ActualProgress); GO

CREATE TABLE pm.ProjectTeam(ProjectTeamId uniqueidentifier PRIMARY KEY DEFAULT NEWSEQUENTIALID(),ProjectId uniqueidentifier NOT NULL,EmployeeId uniqueidentifier NOT NULL,ProjectRole nvarchar(100) NOT NULL,Discipline nvarchar(80) NULL,AllocationPct decimal(5,2) NULL,StartDate date NULL,EndDate date NULL,IsActive bit NOT NULL DEFAULT 1,CreatedAt datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT FK_pm_ProjectTeam_Project FOREIGN KEY(ProjectId) REFERENCES pm.Projects(ProjectId)); GO
CREATE UNIQUE INDEX UX_pm_ProjectTeam ON pm.ProjectTeam(ProjectId,EmployeeId,ProjectRole) WHERE IsActive=1; GO

CREATE TABLE pm.WBS(WbsId uniqueidentifier PRIMARY KEY DEFAULT NEWSEQUENTIALID(),ProjectId uniqueidentifier NOT NULL,ParentWbsId uniqueidentifier NULL,WbsCode nvarchar(60) NOT NULL,WbsName nvarchar(250) NOT NULL,LevelNo tinyint NOT NULL,WeightPct decimal(8,4) NULL,SortOrder int NOT NULL DEFAULT 0,IsActive bit NOT NULL DEFAULT 1,CONSTRAINT FK_pm_WBS_Project FOREIGN KEY(ProjectId) REFERENCES pm.Projects(ProjectId),CONSTRAINT FK_pm_WBS_Parent FOREIGN KEY(ParentWbsId) REFERENCES pm.WBS(WbsId)); GO
CREATE UNIQUE INDEX UX_pm_WBS_Code ON pm.WBS(ProjectId,WbsCode); GO

CREATE TABLE pm.ScheduleActivities(ActivityId uniqueidentifier PRIMARY KEY DEFAULT NEWSEQUENTIALID(),ProjectId uniqueidentifier NOT NULL,WbsId uniqueidentifier NULL,ExternalId nvarchar(80) NULL,ActivityCode nvarchar(80) NOT NULL,ActivityName nvarchar(300) NOT NULL,ActivityType nvarchar(30) NULL,BaselineStart datetime2 NULL,BaselineFinish datetime2 NULL,ForecastStart datetime2 NULL,ForecastFinish datetime2 NULL,ActualStart datetime2 NULL,ActualFinish datetime2 NULL,PercentComplete decimal(7,3) NOT NULL DEFAULT 0,TotalFloatHours decimal(12,2) NULL,IsCritical bit NOT NULL DEFAULT 0,DataDate datetime2 NULL,SourceSystem nvarchar(30) NOT NULL DEFAULT 'DLE Connect',ModifiedAt datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT FK_pm_Activity_Project FOREIGN KEY(ProjectId) REFERENCES pm.Projects(ProjectId),CONSTRAINT FK_pm_Activity_WBS FOREIGN KEY(WbsId) REFERENCES pm.WBS(WbsId)); GO
CREATE INDEX IX_pm_Activities_ProjectCritical ON pm.ScheduleActivities(ProjectId,IsCritical,ForecastFinish); GO

CREATE TABLE pm.Milestones(MilestoneId uniqueidentifier PRIMARY KEY DEFAULT NEWSEQUENTIALID(),ProjectId uniqueidentifier NOT NULL,MilestoneCode nvarchar(50) NOT NULL,Title nvarchar(250) NOT NULL,Category nvarchar(50) NULL,BaselineDate date NULL,ForecastDate date NULL,ActualDate date NULL,OwnerEmployeeId uniqueidentifier NULL,Status nvarchar(30) NOT NULL DEFAULT 'Planned',PercentComplete decimal(7,3) NOT NULL DEFAULT 0,CONSTRAINT FK_pm_Milestone_Project FOREIGN KEY(ProjectId) REFERENCES pm.Projects(ProjectId)); GO

CREATE TABLE pm.EngineeringDeliverables(DeliverableId uniqueidentifier PRIMARY KEY DEFAULT NEWSEQUENTIALID(),ProjectId uniqueidentifier NOT NULL,WbsId uniqueidentifier NULL,DocumentNumber nvarchar(100) NOT NULL,Title nvarchar(300) NOT NULL,Discipline nvarchar(80) NOT NULL,DeliverableType nvarchar(50) NULL,CurrentRevision nvarchar(20) NULL,CurrentStatus nvarchar(50) NOT NULL DEFAULT 'Planned',PlannedIssueDate date NULL,ForecastIssueDate date NULL,ActualIssueDate date NULL,RequiredDate date NULL,OriginatorEmployeeId uniqueidentifier NULL,CheckerEmployeeId uniqueidentifier NULL,ApproverEmployeeId uniqueidentifier NULL,PercentComplete decimal(7,3) NOT NULL DEFAULT 0,EdmsDocumentId nvarchar(100) NULL,CreatedAt datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),ModifiedAt datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT FK_pm_Deliv_Project FOREIGN KEY(ProjectId) REFERENCES pm.Projects(ProjectId)); GO
CREATE UNIQUE INDEX UX_pm_Deliv_DocNo ON pm.EngineeringDeliverables(ProjectId,DocumentNumber); GO

CREATE TABLE pm.DeliverableRevisions(RevisionId uniqueidentifier PRIMARY KEY DEFAULT NEWSEQUENTIALID(),DeliverableId uniqueidentifier NOT NULL,RevisionCode nvarchar(20) NOT NULL,IssuePurpose nvarchar(50) NULL,WorkflowStatus nvarchar(50) NOT NULL,IssuedAt datetime2 NULL,ResponseDueAt datetime2 NULL,RespondedAt datetime2 NULL,FileReference nvarchar(500) NULL,Comments nvarchar(max) NULL,CreatedBy uniqueidentifier NOT NULL,CreatedAt datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT FK_pm_Revision_Deliverable FOREIGN KEY(DeliverableId) REFERENCES pm.EngineeringDeliverables(DeliverableId)); GO

CREATE TABLE pm.Transmittals(TransmittalId uniqueidentifier PRIMARY KEY DEFAULT NEWSEQUENTIALID(),ProjectId uniqueidentifier NOT NULL,TransmittalNumber nvarchar(80) NOT NULL,Direction nvarchar(20) NOT NULL,ToParty nvarchar(200) NOT NULL,Subject nvarchar(300) NULL,IssuedAt datetime2 NOT NULL,ResponseDueAt datetime2 NULL,ResponseAt datetime2 NULL,Status nvarchar(30) NOT NULL DEFAULT 'Issued',CreatedBy uniqueidentifier NOT NULL,CreatedAt datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT FK_pm_Trans_Project FOREIGN KEY(ProjectId) REFERENCES pm.Projects(ProjectId)); GO
CREATE UNIQUE INDEX UX_pm_Transmittals_No ON pm.Transmittals(ProjectId,TransmittalNumber); GO

CREATE TABLE pm.ProcurementPackages(PackageId uniqueidentifier PRIMARY KEY DEFAULT NEWSEQUENTIALID(),ProjectId uniqueidentifier NOT NULL,PackageCode nvarchar(60) NOT NULL,Description nvarchar(300) NOT NULL,Stage nvarchar(50) NOT NULL,VendorId uniqueidentifier NULL,VendorName nvarchar(200) NULL,BudgetValue decimal(19,4) NULL,CommittedValue decimal(19,4) NULL,Currency char(3) NOT NULL DEFAULT 'NGN',RequiredOnSite date NULL,ForecastDelivery date NULL,ActualDelivery date NULL,PercentComplete decimal(7,3) NOT NULL DEFAULT 0,Health nvarchar(20) NOT NULL DEFAULT 'Healthy',SageX3Reference nvarchar(80) NULL,OwnerEmployeeId uniqueidentifier NULL,ModifiedAt datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT FK_pm_Proc_Project FOREIGN KEY(ProjectId) REFERENCES pm.Projects(ProjectId)); GO

CREATE TABLE pm.CostControlAccounts(ControlAccountId uniqueidentifier PRIMARY KEY DEFAULT NEWSEQUENTIALID(),ProjectId uniqueidentifier NOT NULL,WbsId uniqueidentifier NULL,AccountCode nvarchar(60) NOT NULL,AccountName nvarchar(200) NOT NULL,ApprovedBudget decimal(19,4) NOT NULL DEFAULT 0,CommittedCost decimal(19,4) NOT NULL DEFAULT 0,ActualCost decimal(19,4) NOT NULL DEFAULT 0,ForecastCost decimal(19,4) NOT NULL DEFAULT 0,Currency char(3) NOT NULL DEFAULT 'NGN',ModifiedAt datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT FK_pm_Cost_Project FOREIGN KEY(ProjectId) REFERENCES pm.Projects(ProjectId)); GO

CREATE TABLE pm.ProgressPeriods(ProgressPeriodId uniqueidentifier PRIMARY KEY DEFAULT NEWSEQUENTIALID(),ProjectId uniqueidentifier NOT NULL,PeriodEndDate date NOT NULL,DataDate datetime2 NOT NULL,PlannedProgress decimal(7,3) NOT NULL,ActualProgress decimal(7,3) NOT NULL,EarnedValue decimal(19,4) NULL,PlannedValue decimal(19,4) NULL,ActualCost decimal(19,4) NULL,SchedulePerformanceIndex decimal(8,4) NULL,CostPerformanceIndex decimal(8,4) NULL,CertificationStatus nvarchar(30) NOT NULL DEFAULT 'Draft',SubmittedBy uniqueidentifier NULL,SubmittedAt datetime2 NULL,ApprovedBy uniqueidentifier NULL,ApprovedAt datetime2 NULL,CONSTRAINT FK_pm_Progress_Project FOREIGN KEY(ProjectId) REFERENCES pm.Projects(ProjectId),CONSTRAINT UX_pm_Progress UNIQUE(ProjectId,PeriodEndDate)); GO

CREATE TABLE pm.Risks(RiskId uniqueidentifier PRIMARY KEY DEFAULT NEWSEQUENTIALID(),ProjectId uniqueidentifier NOT NULL,RiskCode nvarchar(50) NOT NULL,Title nvarchar(300) NOT NULL,Description nvarchar(max) NULL,Category nvarchar(60) NULL,Type nvarchar(20) NOT NULL DEFAULT 'Risk',ProbabilityScore tinyint NOT NULL,ImpactScore tinyint NOT NULL,InherentScore AS (CONVERT(int,ProbabilityScore)*CONVERT(int,ImpactScore)) PERSISTED,ResidualProbabilityScore tinyint NULL,ResidualImpactScore tinyint NULL,OwnerEmployeeId uniqueidentifier NULL,ResponseStrategy nvarchar(50) NULL,Mitigation nvarchar(max) NULL,DueDate date NULL,Status nvarchar(30) NOT NULL DEFAULT 'Open',Escalated bit NOT NULL DEFAULT 0,CreatedAt datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),ModifiedAt datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT FK_pm_Risk_Project FOREIGN KEY(ProjectId) REFERENCES pm.Projects(ProjectId),CONSTRAINT CK_pm_Risk_Probability CHECK(ProbabilityScore between 1 and 5),CONSTRAINT CK_pm_Risk_Impact CHECK(ImpactScore between 1 and 5)); GO

CREATE TABLE pm.Actions(ActionId uniqueidentifier PRIMARY KEY DEFAULT NEWSEQUENTIALID(),ProjectId uniqueidentifier NOT NULL,ActionCode nvarchar(50) NOT NULL,Title nvarchar(500) NOT NULL,SourceType nvarchar(50) NULL,SourceReference nvarchar(100) NULL,OwnerEmployeeId uniqueidentifier NULL,Priority nvarchar(20) NOT NULL DEFAULT 'Normal',DueDate date NULL,Status nvarchar(30) NOT NULL DEFAULT 'Open',ClosedAt datetime2 NULL,ClosureEvidence nvarchar(1000) NULL,CreatedAt datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),ModifiedAt datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT FK_pm_Action_Project FOREIGN KEY(ProjectId) REFERENCES pm.Projects(ProjectId)); GO

CREATE TABLE pm.Changes(ChangeId uniqueidentifier PRIMARY KEY DEFAULT NEWSEQUENTIALID(),ProjectId uniqueidentifier NOT NULL,ChangeCode nvarchar(50) NOT NULL,Title nvarchar(300) NOT NULL,Origin nvarchar(50) NULL,Description nvarchar(max) NULL,CostImpact decimal(19,4) NULL,ScheduleImpactDays int NULL,RiskImpact nvarchar(50) NULL,Stage nvarchar(50) NOT NULL DEFAULT 'Draft',Status nvarchar(30) NOT NULL DEFAULT 'Open',OwnerEmployeeId uniqueidentifier NULL,ApprovedBy uniqueidentifier NULL,ApprovedAt datetime2 NULL,CreatedAt datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT FK_pm_Change_Project FOREIGN KEY(ProjectId) REFERENCES pm.Projects(ProjectId)); GO

CREATE TABLE pm.NCRs(NcrId uniqueidentifier PRIMARY KEY DEFAULT NEWSEQUENTIALID(),ProjectId uniqueidentifier NOT NULL,NcrCode nvarchar(50) NOT NULL,Title nvarchar(300) NOT NULL,Discipline nvarchar(80) NULL,Severity nvarchar(30) NULL,RaisedAt datetime2 NOT NULL,OwnerEmployeeId uniqueidentifier NULL,RootCause nvarchar(max) NULL,CorrectiveAction nvarchar(max) NULL,DueDate date NULL,Status nvarchar(30) NOT NULL DEFAULT 'Open',ClosedAt datetime2 NULL,CONSTRAINT FK_pm_NCR_Project FOREIGN KEY(ProjectId) REFERENCES pm.Projects(ProjectId)); GO

CREATE TABLE pm.HseEvents(HseEventId uniqueidentifier PRIMARY KEY DEFAULT NEWSEQUENTIALID(),ProjectId uniqueidentifier NOT NULL,EventCode nvarchar(50) NOT NULL,EventType nvarchar(50) NOT NULL,Title nvarchar(300) NOT NULL,Area nvarchar(100) NULL,Severity nvarchar(30) NULL,OccurredAt datetime2 NOT NULL,ReportedAt datetime2 NOT NULL DEFAULT SYSUTCDATETIME(),OwnerEmployeeId uniqueidentifier NULL,Description nvarchar(max) NULL,Status nvarchar(30) NOT NULL DEFAULT 'Open',ClosedAt datetime2 NULL,CONSTRAINT FK_pm_HSE_Project FOREIGN KEY(ProjectId) REFERENCES pm.Projects(ProjectId)); GO

CREATE TABLE pm.ClientInterfaces(InterfaceId uniqueidentifier PRIMARY KEY DEFAULT NEWSEQUENTIALID(),ProjectId uniqueidentifier NOT NULL,ReferenceNo nvarchar(80) NOT NULL,InterfaceType nvarchar(30) NOT NULL,Direction nvarchar(20) NOT NULL,Subject nvarchar(300) NOT NULL,Party nvarchar(200) NOT NULL,IssuedAt datetime2 NOT NULL,ResponseDueAt datetime2 NULL,ResponseAt datetime2 NULL,OwnerEmployeeId uniqueidentifier NULL,Status nvarchar(30) NOT NULL DEFAULT 'Open',CONSTRAINT FK_pm_Interface_Project FOREIGN KEY(ProjectId) REFERENCES pm.Projects(ProjectId)); GO

CREATE TABLE pm.AIAssessments(AiAssessmentId uniqueidentifier PRIMARY KEY DEFAULT NEWSEQUENTIALID(),ProjectId uniqueidentifier NOT NULL,AssessmentType nvarchar(50) NOT NULL,ModelIdentifier nvarchar(100) NOT NULL,PromptHash varbinary(32) NULL,SourceSnapshotId uniqueidentifier NULL,Confidence decimal(5,2) NULL,Summary nvarchar(max) NOT NULL,EvidenceJson nvarchar(max) NULL,RecommendationJson nvarchar(max) NULL,GeneratedAt datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),GeneratedFor uniqueidentifier NOT NULL,HumanDecision nvarchar(30) NULL,HumanDecisionBy uniqueidentifier NULL,HumanDecisionAt datetime2 NULL,CONSTRAINT FK_pm_AI_Project FOREIGN KEY(ProjectId) REFERENCES pm.Projects(ProjectId)); GO

CREATE TABLE pm.AuditLog(AuditId bigint IDENTITY(1,1) PRIMARY KEY,ProjectId uniqueidentifier NULL,EntityName nvarchar(100) NOT NULL,EntityId nvarchar(100) NOT NULL,Action nvarchar(50) NOT NULL,ActorUserId uniqueidentifier NOT NULL,ActorEmployeeId uniqueidentifier NULL,OccurredAt datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),IpAddress varchar(64) NULL,CorrelationId uniqueidentifier NULL,BeforeJson nvarchar(max) NULL,AfterJson nvarchar(max) NULL,Reason nvarchar(500) NULL); GO
CREATE INDEX IX_pm_Audit_ProjectTime ON pm.AuditLog(ProjectId,OccurredAt DESC); GO
