IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name='pm') EXEC('CREATE SCHEMA pm');
GO
CREATE TABLE pm.ProjectCostBaseline(BaselineId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,ProjectId UNIQUEIDENTIFIER NOT NULL,BaselineVersion INT NOT NULL,BaselineName NVARCHAR(120) NOT NULL,ApprovedBudget DECIMAL(19,2) NOT NULL,EffectiveDate DATE NOT NULL,Status NVARCHAR(30) NOT NULL DEFAULT 'Draft',ApprovedBy NVARCHAR(80) NULL,ApprovedAt DATETIME2 NULL,CreatedBy NVARCHAR(80) NOT NULL,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
GO
CREATE TABLE pm.ProjectCostCode(CostCodeId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,ProjectId UNIQUEIDENTIFIER NOT NULL,WbsCode NVARCHAR(50) NOT NULL,CostCode NVARCHAR(50) NOT NULL,Description NVARCHAR(200) NOT NULL,CostCategory NVARCHAR(50) NOT NULL,BudgetAmount DECIMAL(19,2) NOT NULL DEFAULT 0,IsActive BIT NOT NULL DEFAULT 1,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_ProjectCostCode UNIQUE(ProjectId,CostCode));
GO
CREATE TABLE pm.ProjectCommitment(CommitmentId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,ProjectId UNIQUEIDENTIFIER NOT NULL,CostCodeId UNIQUEIDENTIFIER NOT NULL,ReferenceType NVARCHAR(40) NOT NULL,ReferenceNo NVARCHAR(80) NOT NULL,VendorName NVARCHAR(200) NULL,Amount DECIMAL(19,2) NOT NULL,CurrencyCode CHAR(3) NOT NULL DEFAULT 'NGN',CommitmentDate DATE NOT NULL,Status NVARCHAR(30) NOT NULL DEFAULT 'Open',CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
GO
CREATE TABLE pm.ProjectActualCost(ActualCostId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,ProjectId UNIQUEIDENTIFIER NOT NULL,CostCodeId UNIQUEIDENTIFIER NULL,SourceSystem NVARCHAR(50) NOT NULL,SourceReference NVARCHAR(100) NOT NULL,TransactionDate DATE NOT NULL,Amount DECIMAL(19,2) NOT NULL,Description NVARCHAR(300) NULL,IsAllocated BIT NOT NULL DEFAULT 0,ImportedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
GO
CREATE TABLE pm.ProjectTimesheet(TimesheetId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,EmployeeCode NVARCHAR(30) NOT NULL,ProjectId UNIQUEIDENTIFIER NOT NULL,WorkDate DATE NOT NULL,WbsCode NVARCHAR(50) NOT NULL,CostCode NVARCHAR(50) NOT NULL,RegularHours DECIMAL(8,2) NOT NULL DEFAULT 0,OvertimeHours DECIMAL(8,2) NOT NULL DEFAULT 0,WorkflowStatus NVARCHAR(40) NOT NULL DEFAULT 'Draft',SupervisorApprovedAt DATETIME2 NULL,ProjectManagerApprovedAt DATETIME2 NULL,CostControlApprovedAt DATETIME2 NULL,HrApprovedAt DATETIME2 NULL,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT CK_ProjectTimesheet_Hours CHECK(RegularHours>=0 AND OvertimeHours>=0 AND RegularHours+OvertimeHours<=24));
GO
CREATE TABLE pm.ProjectManHourBudget(ManHourBudgetId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,ProjectId UNIQUEIDENTIFIER NOT NULL,Discipline NVARCHAR(80) NOT NULL,PlannedHours DECIMAL(18,2) NOT NULL,ForecastHours DECIMAL(18,2) NULL,EffectivePeriod CHAR(7) NOT NULL,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
GO
CREATE TABLE pm.ProjectCostForecast(ForecastId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,ProjectId UNIQUEIDENTIFIER NOT NULL,Period CHAR(7) NOT NULL,BAC DECIMAL(19,2) NOT NULL,ActualCost DECIMAL(19,2) NOT NULL,ETC DECIMAL(19,2) NOT NULL,EAC AS (ActualCost+ETC) PERSISTED,ForecastStatus NVARCHAR(30) NOT NULL DEFAULT 'Draft',SubmittedBy NVARCHAR(80) NULL,SubmittedAt DATETIME2 NULL,ApprovedBy NVARCHAR(80) NULL,ApprovedAt DATETIME2 NULL,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
GO
CREATE TABLE pm.ProjectCostAlert(AlertId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,ProjectId UNIQUEIDENTIFIER NOT NULL,AlertType NVARCHAR(50) NOT NULL,Severity NVARCHAR(20) NOT NULL,Title NVARCHAR(200) NOT NULL,Description NVARCHAR(500) NULL,Status NVARCHAR(30) NOT NULL DEFAULT 'Open',OwnerEmployeeCode NVARCHAR(30) NULL,DueDate DATE NULL,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
GO
CREATE INDEX IX_ProjectTimesheet_ProjectDate ON pm.ProjectTimesheet(ProjectId,WorkDate);
CREATE INDEX IX_ProjectActualCost_ProjectDate ON pm.ProjectActualCost(ProjectId,TransactionDate);
CREATE INDEX IX_ProjectCommitment_ProjectDate ON pm.ProjectCommitment(ProjectId,CommitmentDate);
GO
