export type PeModuleDefinition = {
  id: string;
  title: string;
  subtitle: string;
  href: string;
  kpis: Array<{ label: string; value: string; hint: string; tone?: 'blue' | 'indigo' | 'cyan' | 'amber' | 'rose' | 'purple' }>;
  columns: string[];
  emptyTitle: string;
  emptyBody: string;
  primaryAction?: { label: string; href: string };
  secondaryAction?: { label: string; href: string };
  related: Array<{ label: string; href: string }>;
};

/** Portfolio-level EPC modules (non-placeholder business frames). */
export const PE_MODULE_CATALOG: PeModuleDefinition[] = [
  {
    id: 'planning',
    title: 'Planning & Schedule',
    subtitle: 'WBS, baselines, critical path, look-ahead and SPI control for the DLE portfolio.',
    href: '/projects-engineering/planning',
    kpis: [
      { label: 'Active Schedules', value: '—', hint: 'Projects with baseline', tone: 'blue' },
      { label: 'Critical Path Items', value: '—', hint: 'Near-critical + critical', tone: 'amber' },
      { label: 'Avg SPI', value: '—', hint: 'Portfolio schedule index', tone: 'indigo' },
      { label: 'Look-Ahead', value: '2 / 4 / 90', hint: 'Week windows', tone: 'cyan' },
    ],
    columns: ['Project', 'Baseline Finish', 'Forecast Finish', 'SPI', 'Critical Activities', 'Look-Ahead', 'Health'],
    emptyTitle: 'No schedule baseline loaded',
    emptyBody: 'Import or create a baseline schedule for a project. P6 integration can sync activities once connectors are configured.',
    primaryAction: { label: 'Open Projects', href: '/projects-engineering/projects' },
    secondaryAction: { label: 'Integrations', href: '/projects-engineering/integrations' },
    related: [
      { label: 'Progress Measurement', href: '/projects-engineering/progress' },
      { label: 'Cost Control', href: '/projects-engineering/cost-control' },
    ],
  },
  {
    id: 'timesheets',
    title: 'Timesheets & Man-Hours',
    subtitle: 'Supervisor → PM → Cost Control → HR → Payroll. Live utilisation from approved project allocations.',
    href: '/projects-engineering/timesheets',
    kpis: [
      { label: 'Booked MH', value: 'Live', hint: 'PM-approved+ hours', tone: 'rose' },
      { label: 'MH Budget', value: 'Live', hint: 'pm.ManHourBudgets', tone: 'indigo' },
      { label: 'Utilisation', value: 'Live', hint: 'Actual / budget', tone: 'blue' },
      { label: 'Queue', value: 'Live', hint: 'Awaiting Cost Control', tone: 'amber' },
    ],
    columns: ['Project', 'Booked Hours', 'Budget Hours', 'Utilisation %', 'Employees', 'Pending Validation', 'Open'],
    emptyTitle: 'No man-hour bookings in scope',
    emptyBody: 'Approved timesheet allocations against project codes appear here. Open a project Man Hours workspace to set budgets and review utilisation.',
    primaryAction: { label: 'HRIS Timesheet Entry', href: '/hris/time-and-logs/timesheet-entry' },
    secondaryAction: { label: 'Cost Control Labour', href: '/projects-engineering/cost-control' },
    related: [
      { label: 'Resources', href: '/projects-engineering/resources' },
      { label: 'Portfolio Dashboard', href: '/projects-engineering' },
    ],
  },
  {
    id: 'resources',
    title: 'Resources',
    subtitle: 'Project team allocation, demand vs capacity, mobilisation and over-allocation control.',
    href: '/projects-engineering/resources',
    kpis: [
      { label: 'Assigned People', value: '—', hint: 'Directory + project teams', tone: 'blue' },
      { label: 'Over-allocated', value: '—', hint: 'Conflicts', tone: 'rose' },
      { label: 'Mobilisations', value: '—', hint: 'Active crew moves', tone: 'cyan' },
      { label: 'Utilisation', value: '—', hint: 'Portfolio average', tone: 'indigo' },
    ],
    columns: ['Employee', 'Code', 'Discipline', 'Projects', 'Hours (period)', 'Allocation %', 'Status'],
    emptyTitle: 'No resource assignments loaded',
    emptyBody: 'Assign project teams from the employee directory or open a project Man Hours workspace to review booked people.',
    primaryAction: { label: 'Employee Directory', href: '/hris/employees/employee-directory' },
    secondaryAction: { label: 'Timesheets & Man-Hours', href: '/projects-engineering/timesheets' },
    related: [{ label: 'Planning & Schedule', href: '/projects-engineering/planning' }],
  },
  {
    id: 'progress',
    title: 'Progress Measurement',
    subtitle: 'Physical, planned and earned progress — not derived solely from money spent.',
    href: '/projects-engineering/progress',
    kpis: [
      { label: 'Avg Physical %', value: '—', hint: 'Portfolio', tone: 'blue' },
      { label: 'Avg Planned %', value: '—', hint: 'Baseline', tone: 'indigo' },
      { label: 'Variance', value: '—', hint: 'Actual − Planned', tone: 'amber' },
      { label: 'Evidence Packs', value: '—', hint: 'Period submissions', tone: 'cyan' },
    ],
    columns: ['Project', 'Planned %', 'Actual %', 'Earned %', 'SPI', 'Period', 'Status'],
    emptyTitle: 'No progress periods recorded',
    emptyBody: 'Capture weighted physical progress by discipline/WBS for each reporting period.',
    primaryAction: { label: 'Open Projects', href: '/projects-engineering/projects' },
    related: [
      { label: 'Planning & Schedule', href: '/projects-engineering/planning' },
      { label: 'Cost Control EVM', href: '/projects-engineering/cost-control' },
    ],
  },
  {
    id: 'engineering',
    title: 'Engineering',
    subtitle: 'Discipline dashboards, design deliverables, reviews, TQs and engineering man-hours.',
    href: '/projects-engineering/engineering',
    kpis: [
      { label: 'Open Deliverables', value: '—', hint: 'IFR/IFA/IFC', tone: 'blue' },
      { label: 'Overdue', value: '—', hint: 'Past planned issue', tone: 'rose' },
      { label: 'TQs Open', value: '—', hint: 'Technical queries', tone: 'amber' },
      { label: 'Eng. MH', value: '—', hint: 'Booked engineering hours', tone: 'indigo' },
    ],
    columns: ['Document No.', 'Title', 'Discipline', 'Status', 'Planned Issue', 'Forecast', 'Owner'],
    emptyTitle: 'No engineering deliverables registered',
    emptyBody: 'Seed the Master Deliverables Register or open Document Control to start controlled engineering issue cycles.',
    primaryAction: { label: 'Deliverables Register', href: '/projects-engineering/deliverables' },
    secondaryAction: { label: 'Document Control', href: '/projects-engineering/document-control' },
    related: [{ label: 'Interfaces', href: '/projects-engineering/interfaces' }],
  },
  {
    id: 'deliverables',
    title: 'Deliverables Register (MDR)',
    subtitle: 'Master deliverables with weighting, revision, client status and schedule impact.',
    href: '/projects-engineering/deliverables',
    kpis: [
      { label: 'Register Size', value: '—', hint: 'Active documents', tone: 'blue' },
      { label: 'Overdue', value: '—', hint: 'Past planned date', tone: 'rose' },
      { label: 'In Client Review', value: '—', hint: 'Awaiting code', tone: 'amber' },
      { label: 'IFC+', value: '—', hint: 'Issued for construction', tone: 'cyan' },
    ],
    columns: ['Doc No.', 'Title', 'Discipline', 'Rev', 'Status', 'Planned', 'Actual', 'Weight %'],
    emptyTitle: 'MDR is empty',
    emptyBody: 'Create deliverables against a project WBS. Overdue items will surface on the Portfolio Dashboard.',
    primaryAction: { label: 'Engineering', href: '/projects-engineering/engineering' },
    related: [{ label: 'Document Control', href: '/projects-engineering/document-control' }],
  },
  {
    id: 'document-control',
    title: 'Document Control',
    subtitle: 'Incoming/outgoing, transmittals, revisions, distribution and controlled history.',
    href: '/projects-engineering/document-control',
    kpis: [
      { label: 'Controlled Docs', value: '—', hint: 'Live register', tone: 'blue' },
      { label: 'Open Transmittals', value: '—', hint: 'Awaiting acknowledgement', tone: 'amber' },
      { label: 'Superseded', value: '—', hint: 'Historic revisions retained', tone: 'indigo' },
      { label: 'Handover Pack', value: '—', hint: 'As-built readiness', tone: 'cyan' },
    ],
    columns: ['Doc No.', 'Title', 'Rev', 'Type', 'Direction', 'Status', 'Transmittal', 'Updated'],
    emptyTitle: 'No controlled documents yet',
    emptyBody: 'Register documents without overwriting history. EDMS/CDE connectors can sync when configured.',
    primaryAction: { label: 'Integrations', href: '/projects-engineering/integrations' },
    related: [{ label: 'Deliverables', href: '/projects-engineering/deliverables' }],
  },
  {
    id: 'procurement',
    title: 'Procurement & Expediting',
    subtitle: 'PR → RFQ → PO/Subcontract, long-lead tracking and commitment linkage to Cost Control.',
    href: '/projects-engineering/procurement',
    kpis: [
      { label: 'Open POs', value: '—', hint: 'Active commitments', tone: 'blue' },
      { label: 'Long Lead', value: '—', hint: 'Critical packages', tone: 'rose' },
      { label: 'Late Deliveries', value: '—', hint: 'Vs promise date', tone: 'amber' },
      { label: 'Commitments', value: '—', hint: 'Linked to cost', tone: 'indigo' },
    ],
    columns: ['Package', 'Vendor', 'PO / Subcon', 'ROS Date', 'Promise', 'Forecast', 'Status'],
    emptyTitle: 'No procurement packages',
    emptyBody: 'Create packages and link commitments so Cost Control can validate budget availability.',
    primaryAction: { label: 'Cost Control Commitments', href: '/projects-engineering/cost-control' },
    related: [{ label: 'Commercial', href: '/projects-engineering/commercial' }],
  },
  {
    id: 'construction',
    title: 'Construction / Fabrication',
    subtitle: 'CWPs, fabrication packages, quantities, punch, productivity and look-ahead.',
    href: '/projects-engineering/construction',
    kpis: [
      { label: 'Open CWPs', value: '—', hint: 'Work packages', tone: 'blue' },
      { label: 'Qty Progress', value: '—', hint: 'Planned vs actual', tone: 'cyan' },
      { label: 'Punch Open', value: '—', hint: 'Outstanding items', tone: 'amber' },
      { label: 'Constraints', value: '—', hint: 'Blocking work fronts', tone: 'rose' },
    ],
    columns: ['Package', 'Discipline', 'Planned Qty', 'Actual Qty', 'Progress %', 'Constraints', 'Status'],
    emptyTitle: 'No construction / fabrication packages',
    emptyBody: 'Create work packages and capture daily quantities with evidence where required.',
    primaryAction: { label: 'Progress Measurement', href: '/projects-engineering/progress' },
    related: [{ label: 'Quality', href: '/projects-engineering/quality' }],
  },
  {
    id: 'commercial',
    title: 'Commercial & Contracts',
    subtitle: 'Contract value, certificates, retention, variations and commercial forecast — integrated with Cost Control.',
    href: '/projects-engineering/commercial',
    kpis: [
      { label: 'Contract Value', value: '—', hint: 'Original + approved VO', tone: 'blue' },
      { label: 'Certified', value: '—', hint: 'Interim certificates', tone: 'indigo' },
      { label: 'Retention', value: '—', hint: 'Held', tone: 'amber' },
      { label: 'Unapproved VO', value: '—', hint: 'Commercial exposure', tone: 'rose' },
    ],
    columns: ['Project', 'Contract Value', 'Certified', 'Billed', 'Received', 'Retention', 'Status'],
    emptyTitle: 'No commercial register rows',
    emptyBody: 'Capture contract baselines and certificates. Commercial data stays segregated from Cost Control roles.',
    primaryAction: { label: 'Billing & Certificates', href: '/projects-engineering/commercial/billing' },
    secondaryAction: { label: 'Variations', href: '/projects-engineering/changes' },
    related: [{ label: 'Claims & Notices', href: '/projects-engineering/commercial/claims' }],
  },
  {
    id: 'billing',
    title: 'Client Billing & Certificates',
    subtitle: 'Payment applications, interim certificates, retention, ageing and cash received.',
    href: '/projects-engineering/commercial/billing',
    kpis: [
      { label: 'Applications', value: '—', hint: 'This period', tone: 'blue' },
      { label: 'Net Certified', value: '—', hint: 'After retention', tone: 'indigo' },
      { label: 'Outstanding', value: '—', hint: 'Ageing', tone: 'amber' },
      { label: 'Received', value: '—', hint: 'Cash', tone: 'cyan' },
    ],
    columns: ['Certificate', 'Project', 'Period', 'Gross', 'Retention', 'Net', 'Status'],
    emptyTitle: 'No certificates yet',
    emptyBody: 'Raise a payment application from Commercial once progress valuation is approved.',
    primaryAction: { label: 'Commercial Overview', href: '/projects-engineering/commercial' },
    related: [{ label: 'Progress', href: '/projects-engineering/progress' }],
  },
  {
    id: 'claims',
    title: 'Claims & Notices',
    subtitle: 'EOT, cost claims, notices, deadlines and commercial impact with evidence.',
    href: '/projects-engineering/commercial/claims',
    kpis: [
      { label: 'Open Claims', value: '—', hint: 'Active', tone: 'amber' },
      { label: 'Notices Due', value: '—', hint: 'Deadline alerts', tone: 'rose' },
      { label: 'Submitted Value', value: '—', hint: 'Exposure', tone: 'indigo' },
      { label: 'Approved Value', value: '—', hint: 'Settled', tone: 'cyan' },
    ],
    columns: ['Ref', 'Type', 'Project', 'Submitted', 'Deadline', 'Value', 'Status'],
    emptyTitle: 'No claims or notices',
    emptyBody: 'Log potential claims early and link supporting correspondence from Interfaces.',
    primaryAction: { label: 'Interfaces', href: '/projects-engineering/interfaces' },
    related: [{ label: 'Changes & Variations', href: '/projects-engineering/changes' }],
  },
  {
    id: 'changes',
    title: 'Changes & Variations',
    subtitle: 'Controlled change lifecycle from draft through commercial assessment to baseline update.',
    href: '/projects-engineering/changes',
    kpis: [
      { label: 'Open Changes', value: '—', hint: 'In workflow', tone: 'amber' },
      { label: 'Approved VO', value: '—', hint: 'Value', tone: 'indigo' },
      { label: 'Schedule Impact', value: '—', hint: 'Days', tone: 'rose' },
      { label: 'Awaiting Client', value: '—', hint: 'Submitted', tone: 'blue' },
    ],
    columns: ['CR No.', 'Project', 'Origin', 'Cost Impact', 'Schedule Impact', 'Stage', 'Status'],
    emptyTitle: 'No change requests',
    emptyBody: 'Raise a change request with technical, cost, schedule and HSE impact assessments.',
    primaryAction: { label: 'Commercial', href: '/projects-engineering/commercial' },
    related: [{ label: 'Cost Control Variations', href: '/projects-engineering/cost-control' }],
  },
  {
    id: 'quality',
    title: 'Quality Management',
    subtitle: 'ITP, inspections, NCR/CAR, punch and quality dossier readiness.',
    href: '/projects-engineering/quality',
    kpis: [
      { label: 'Open NCRs', value: '—', hint: 'Active', tone: 'rose' },
      { label: 'Overdue NCRs', value: '—', hint: 'Past target', tone: 'amber' },
      { label: 'Pass Rate', value: '—', hint: 'Inspections', tone: 'cyan' },
      { label: 'Punch Open', value: '—', hint: 'Items', tone: 'indigo' },
    ],
    columns: ['Ref', 'Type', 'Project', 'Discipline', 'Raised', 'Due', 'Status'],
    emptyTitle: 'No quality records',
    emptyBody: 'Create ITPs and inspection requests. NCRs will escalate to Portfolio alerts when overdue.',
    primaryAction: { label: 'Construction', href: '/projects-engineering/construction' },
    related: [{ label: 'Closeout', href: '/projects-engineering/closeout' }],
  },
  {
    id: 'hse',
    title: 'HSE Management',
    subtitle: 'Incidents, observations, PTW, toolbox talks, actions and leading indicators.',
    href: '/projects-engineering/hse',
    kpis: [
      { label: 'LTI', value: '—', hint: 'Period', tone: 'rose' },
      { label: 'Near Misses', value: '—', hint: 'Reported', tone: 'amber' },
      { label: 'Open Actions', value: '—', hint: 'Corrective', tone: 'indigo' },
      { label: 'Safe MH', value: '—', hint: 'Worked hours', tone: 'cyan' },
    ],
    columns: ['Event', 'Type', 'Project', 'Severity', 'Date', 'Owner', 'Status'],
    emptyTitle: 'No HSE events logged',
    emptyBody: 'Capture incidents, near misses and observations. Link corrective actions to Meetings & Actions.',
    primaryAction: { label: 'Actions', href: '/projects-engineering/actions' },
    related: [{ label: 'Resources', href: '/projects-engineering/resources' }],
  },
  {
    id: 'risks',
    title: 'Risks, Issues & Opportunities',
    subtitle: 'Risk matrix, mitigations, residual exposure and contingency linkage.',
    href: '/projects-engineering/risks',
    kpis: [
      { label: 'Open Risks', value: '—', hint: 'Active', tone: 'amber' },
      { label: 'Critical', value: '—', hint: 'High residual', tone: 'rose' },
      { label: 'Cost Exposure', value: '—', hint: '₦', tone: 'indigo' },
      { label: 'Opportunities', value: '—', hint: 'Tracked', tone: 'cyan' },
    ],
    columns: ['ID', 'Title', 'Project', 'Likelihood', 'Impact', 'Residual', 'Owner'],
    emptyTitle: 'Risk register is empty',
    emptyBody: 'Log risks with cost/schedule exposure. AI may suggest candidates but humans accept residual risk.',
    primaryAction: { label: 'AI Intelligence', href: '/projects-engineering/ai-intelligence' },
    related: [{ label: 'Cost Control', href: '/projects-engineering/cost-control' }],
  },
  {
    id: 'actions',
    title: 'Meetings, Actions & Decisions',
    subtitle: 'Minutes, actions, decisions and escalations across all project modules.',
    href: '/projects-engineering/actions',
    kpis: [
      { label: 'Open Actions', value: '—', hint: 'All projects', tone: 'amber' },
      { label: 'Overdue', value: '—', hint: 'Past due', tone: 'rose' },
      { label: 'My Actions', value: '—', hint: 'Assigned to you', tone: 'blue' },
      { label: 'Meetings (30d)', value: '—', hint: 'Recorded', tone: 'indigo' },
    ],
    columns: ['Action', 'Project', 'Owner', 'Source', 'Due', 'Priority', 'Status'],
    emptyTitle: 'No actions recorded',
    emptyBody: 'Actions can originate from meetings, risks, NCRs, client interfaces and cost exceptions.',
    primaryAction: { label: 'Portfolio Dashboard', href: '/projects-engineering' },
    related: [{ label: 'Interfaces', href: '/projects-engineering/interfaces' }],
  },
  {
    id: 'interfaces',
    title: 'Client / Contractor Interface',
    subtitle: 'RFI, TQ, correspondence, response deadlines and escalations.',
    href: '/projects-engineering/interfaces',
    kpis: [
      { label: 'Open RFIs', value: '—', hint: 'Awaiting response', tone: 'amber' },
      { label: 'Overdue', value: '—', hint: 'Past deadline', tone: 'rose' },
      { label: 'TQs', value: '—', hint: 'Technical queries', tone: 'blue' },
      { label: 'Commitments', value: '—', hint: 'Client/contractor', tone: 'indigo' },
    ],
    columns: ['Ref', 'Type', 'Project', 'Subject', 'Deadline', 'Owner', 'Status'],
    emptyTitle: 'No interface items',
    emptyBody: 'Log RFIs and correspondence with deadlines. Overdue client responses appear on Portfolio alerts.',
    primaryAction: { label: 'Document Control', href: '/projects-engineering/document-control' },
    related: [{ label: 'Engineering', href: '/projects-engineering/engineering' }],
  },
  {
    id: 'reports-portfolio',
    title: 'Portfolio Reports',
    subtitle: 'Executive portfolio packs — cost, schedule, man-hours, commercial, quality and HSE.',
    href: '/projects-engineering/reports/portfolio',
    kpis: [
      { label: 'Report Packs', value: '12', hint: 'Available templates', tone: 'blue' },
      { label: 'Last Generated', value: '—', hint: 'UTC', tone: 'indigo' },
      { label: 'Exports', value: 'Excel / PDF', hint: 'Supported', tone: 'cyan' },
      { label: 'Audience', value: 'MD / PMO', hint: 'Role packs', tone: 'amber' },
    ],
    columns: ['Report', 'Audience', 'Period', 'Format', 'Last Run', 'Owner', 'Action'],
    emptyTitle: 'No generated portfolio reports yet',
    emptyBody: 'Select a template and reporting period. Live KPIs pull from projects, cost snapshots and man-hours.',
    primaryAction: { label: 'Portfolio Dashboard', href: '/projects-engineering' },
    related: [{ label: 'Project Reports', href: '/projects-engineering/reports/project' }],
  },
  {
    id: 'reports-project',
    title: 'Project Reports',
    subtitle: 'Daily / weekly / monthly controls, client and executive summaries by project.',
    href: '/projects-engineering/reports/project',
    kpis: [
      { label: 'Templates', value: '16', hint: 'Project packs', tone: 'blue' },
      { label: 'Projects', value: '—', hint: 'In scope', tone: 'indigo' },
      { label: 'Pending Approval', value: '—', hint: 'Draft reports', tone: 'amber' },
      { label: 'Published', value: '—', hint: 'This month', tone: 'cyan' },
    ],
    columns: ['Project', 'Report Type', 'Period', 'Status', 'Author', 'Published', 'Open'],
    emptyTitle: 'Select a project to generate reports',
    emptyBody: 'Open a project workspace then use Project Reports for period-based packs.',
    primaryAction: { label: 'Projects', href: '/projects-engineering/projects' },
    related: [{ label: 'Portfolio Reports', href: '/projects-engineering/reports/portfolio' }],
  },
  {
    id: 'closeout',
    title: 'Project Closeout & Handover',
    subtitle: 'Mechanical completion, dossiers, commercial close, client acceptance and archive.',
    href: '/projects-engineering/closeout',
    kpis: [
      { label: 'Readiness', value: '—', hint: 'Score / 100', tone: 'blue' },
      { label: 'Punch Open', value: '—', hint: 'Blocking', tone: 'amber' },
      { label: 'Docs Pending', value: '—', hint: 'As-built', tone: 'indigo' },
      { label: 'Commercial Open', value: '—', hint: 'Claims / VO', tone: 'rose' },
    ],
    columns: ['Checklist Item', 'Project', 'Owner', 'Mandatory', 'Status', 'Evidence', 'Due'],
    emptyTitle: 'No closeout checklists started',
    emptyBody: 'Open a project closeout pack. Final closure is blocked while mandatory items remain open.',
    primaryAction: { label: 'Lessons Learned', href: '/projects-engineering/lessons-learned' },
    related: [{ label: 'Quality', href: '/projects-engineering/quality' }],
  },
  {
    id: 'lessons',
    title: 'Lessons Learned',
    subtitle: 'Capture reusable lessons during and after projects with evidence and confidentiality.',
    href: '/projects-engineering/lessons-learned',
    kpis: [
      { label: 'Lessons', value: '—', hint: 'Library', tone: 'blue' },
      { label: 'Reusable', value: '—', hint: 'Tagged', tone: 'cyan' },
      { label: 'This Year', value: '—', hint: 'Captured', tone: 'indigo' },
      { label: 'AI Matches', value: '—', hint: 'Suggested', tone: 'amber' },
    ],
    columns: ['Lesson', 'Project', 'Phase', 'Discipline', 'Impact', 'Reusable', 'Owner'],
    emptyTitle: 'No lessons captured',
    emptyBody: 'Record situation, root cause, impact and recommendation. AI can retrieve similar historical lessons.',
    primaryAction: { label: 'AI Intelligence', href: '/projects-engineering/ai-intelligence' },
    related: [{ label: 'Closeout', href: '/projects-engineering/closeout' }],
  },
  {
    id: 'ai',
    title: 'AI Project Intelligence',
    subtitle: 'Advisory insights with reason, source, confidence and recommended action — humans remain accountable.',
    href: '/projects-engineering/ai-intelligence',
    kpis: [
      { label: 'Insights', value: '—', hint: 'Open', tone: 'blue' },
      { label: 'High Confidence', value: '—', hint: '≥ 80%', tone: 'indigo' },
      { label: 'Cost Alerts', value: '—', hint: 'EAC / CPI', tone: 'rose' },
      { label: 'Schedule Alerts', value: '—', hint: 'SPI / finish', tone: 'amber' },
    ],
    columns: ['Insight', 'Project', 'Confidence', 'Source', 'Generated', 'Action', 'Status'],
    emptyTitle: 'No AI insights generated yet',
    emptyBody: 'Insights appear as project, cost, schedule and man-hour data accumulates. Recommendations are advisory only.',
    primaryAction: { label: 'Portfolio Dashboard', href: '/projects-engineering' },
    related: [{ label: 'Risks', href: '/projects-engineering/risks' }],
  },
  {
    id: 'admin',
    title: 'Project Administration',
    subtitle: 'Roles, approval matrices, calendars, disciplines, cost categories and health rules.',
    href: '/projects-engineering/admin',
    kpis: [
      { label: 'Matrices', value: '—', hint: 'Approval', tone: 'blue' },
      { label: 'Disciplines', value: '—', hint: 'Configured', tone: 'indigo' },
      { label: 'Cost Codes', value: '—', hint: 'CBS nodes', tone: 'cyan' },
      { label: 'Teams', value: '—', hint: 'Project roles', tone: 'amber' },
    ],
    columns: ['Setting', 'Scope', 'Owner', 'Last Change', 'Audit', 'Status'],
    emptyTitle: 'Administration catalogue ready',
    emptyBody: 'Configure project roles and matrices. Changes require permission and are audited.',
    primaryAction: { label: 'Configuration', href: '/projects-engineering/configuration' },
    related: [{ label: 'Integrations', href: '/projects-engineering/integrations' }],
  },
  {
    id: 'configuration',
    title: 'Configuration',
    subtitle: 'Numbering, timesheet/MH rules, EVM, period close, alerts, retention and AI governance.',
    href: '/projects-engineering/configuration',
    kpis: [
      { label: 'Rule Sets', value: '—', hint: 'Active', tone: 'blue' },
      { label: 'Period Close', value: '—', hint: 'Policy', tone: 'indigo' },
      { label: 'Alerts', value: '—', hint: 'Enabled', tone: 'amber' },
      { label: 'AI Governance', value: 'On', hint: 'Advisory mode', tone: 'cyan' },
    ],
    columns: ['Domain', 'Rule', 'Value', 'Changed By', 'Changed At', 'Status'],
    emptyTitle: 'Configuration console',
    emptyBody: 'Adjust controlled settings. Every change writes an immutable audit event.',
    primaryAction: { label: 'Project Administration', href: '/projects-engineering/admin' },
    related: [{ label: 'Integrations', href: '/projects-engineering/integrations' }],
  },
  {
    id: 'workspace',
    title: 'Active Project Workspace',
    subtitle: 'Jump to a live project command centre — health, controls, commercial and assurance in one place.',
    href: '/projects-engineering/workspace',
    kpis: [
      { label: 'Projects In Scope', value: 'Live', hint: 'Your access', tone: 'blue' },
      { label: 'At Risk', value: 'Live', hint: 'Watch + Critical', tone: 'amber' },
      { label: 'Open Alerts', value: 'Live', hint: 'Cross-module', tone: 'rose' },
      { label: 'MH Booked', value: 'Live', hint: 'Timesheets', tone: 'indigo' },
    ],
    columns: ['Project', 'PM', 'Progress', 'SPI/CPI', 'MH Util', 'Health', 'Open'],
    emptyTitle: 'No projects in your workspace scope',
    emptyBody: 'Ask IT to assign you as Project Manager or grant portfolio access.',
    primaryAction: { label: 'Projects Register', href: '/projects-engineering/projects' },
    related: [{ label: 'Portfolio Dashboard', href: '/projects-engineering' }],
  },
];

export const getPeModule = (id: string) => PE_MODULE_CATALOG.find((item) => item.id === id) || null;
