-- DLE Connect Timesheet Management Portal
-- SQL Server production-oriented schema. Existing HR/Project masters are referenced through integration keys.
SET ANSI_NULLS ON; SET QUOTED_IDENTIFIER ON;

IF OBJECT_ID('dbo.TS_PersonIdentity','U') IS NULL
CREATE TABLE dbo.TS_PersonIdentity(PermanentPersonId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY, DisplayName NVARCHAR(250) NOT NULL, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
GO

IF OBJECT_ID('dbo.TS_EmploymentEpisode','U') IS NULL
CREATE TABLE dbo.TS_EmploymentEpisode(EmploymentEpisodeId BIGINT IDENTITY PRIMARY KEY, PermanentPersonId UNIQUEIDENTIFIER NOT NULL, EmployeeCode NVARCHAR(30) NOT NULL, StartDate DATE NOT NULL, EndDate DATE NULL, EmploymentStatus NVARCHAR(30) NOT NULL, CONSTRAINT UQ_TS_Employment UNIQUE(EmployeeCode,StartDate));
GO

IF OBJECT_ID('dbo.TS_BiometricIdentity','U') IS NULL
CREATE TABLE dbo.TS_BiometricIdentity(BiometricIdentityId BIGINT IDENTITY PRIMARY KEY, PermanentPersonId UNIQUEIDENTIFIER NOT NULL, DeviceId NVARCHAR(80) NOT NULL, BiometricUserId NVARCHAR(80) NOT NULL, IsLegacy BIT NOT NULL DEFAULT 0, ValidFrom DATETIME2 NOT NULL, ValidTo DATETIME2 NULL, Status NVARCHAR(20) NOT NULL, ApprovedBy NVARCHAR(80) NULL);
GO

IF OBJECT_ID('dbo.TS_RawBiometricPunch','U') IS NULL
CREATE TABLE dbo.TS_RawBiometricPunch(RawPunchId BIGINT IDENTITY PRIMARY KEY, DeviceId NVARCHAR(80) NOT NULL, BiometricUserId NVARCHAR(80) NOT NULL, PunchTimestamp DATETIME2 NOT NULL, DeviceEventType NVARCHAR(30) NULL, RawPayload NVARCHAR(MAX) NULL, ReceivedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), CONSTRAINT UQ_TS_RawPunch UNIQUE(DeviceId,BiometricUserId,PunchTimestamp));
GO

IF OBJECT_ID('dbo.TS_CrewAssignment','U') IS NULL
CREATE TABLE dbo.TS_CrewAssignment(CrewAssignmentId BIGINT IDENTITY PRIMARY KEY, PermanentPersonId UNIQUEIDENTIFIER NOT NULL, SupervisorPersonId UNIQUEIDENTIFIER NOT NULL, DepartmentCode NVARCHAR(40) NULL, LocationCode NVARCHAR(40) NOT NULL, WorkCentreCode NVARCHAR(40) NULL, AssignmentType NVARCHAR(30) NOT NULL, EffectiveFrom DATE NOT NULL, EffectiveTo DATE NULL, OperationalStatus NVARCHAR(40) NOT NULL, Reason NVARCHAR(500) NULL);
GO

IF OBJECT_ID('dbo.TS_Mobilization','U') IS NULL
CREATE TABLE dbo.TS_Mobilization(MobilizationId BIGINT IDENTITY PRIMARY KEY, PermanentPersonId UNIQUEIDENTIFIER NOT NULL, ProjectCode NVARCHAR(40) NOT NULL, OffshoreLocation NVARCHAR(120) NOT NULL, MobilizedFrom DATE NOT NULL, ExpectedReturn DATE NULL, ActualReturn DATE NULL, Status NVARCHAR(30) NOT NULL, ReferenceNo NVARCHAR(80) NULL, OffshoreSupervisorId UNIQUEIDENTIFIER NULL);
GO

IF OBJECT_ID('dbo.TS_Period','U') IS NULL
CREATE TABLE dbo.TS_Period(TimesheetPeriodId BIGINT IDENTITY PRIMARY KEY, PeriodCode NVARCHAR(30) NOT NULL UNIQUE, PeriodName NVARCHAR(100) NOT NULL, StartDate DATE NOT NULL, EndDate DATE NOT NULL, CaptureDeadline DATETIME2 NULL, ReviewDeadline DATETIME2 NULL, ApprovalDeadline DATETIME2 NULL, Status NVARCHAR(30) NOT NULL, OpenedBy NVARCHAR(80) NULL, OpenedAt DATETIME2 NULL, CaptureClosedAt DATETIME2 NULL, PayrollLockedAt DATETIME2 NULL, ClosedAt DATETIME2 NULL);
GO

IF OBJECT_ID('dbo.TS_Header','U') IS NULL
CREATE TABLE dbo.TS_Header(TimesheetHeaderId BIGINT IDENTITY PRIMARY KEY, TimesheetPeriodId BIGINT NOT NULL, WorkDate DATE NOT NULL, SupervisorPersonId UNIQUEIDENTIFIER NOT NULL, LocationCode NVARCHAR(40) NOT NULL, WorkCentreCode NVARCHAR(40) NULL, ShiftCode NVARCHAR(40) NULL, CapturedBy NVARCHAR(80) NOT NULL, Status NVARCHAR(40) NOT NULL, VersionNo INT NOT NULL DEFAULT 1, LastSavedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
GO

IF OBJECT_ID('dbo.TS_EmployeeDay','U') IS NULL
CREATE TABLE dbo.TS_EmployeeDay(EmployeeDayId BIGINT IDENTITY PRIMARY KEY, TimesheetHeaderId BIGINT NOT NULL, PermanentPersonId UNIQUEIDENTIFIER NOT NULL, EmploymentEpisodeId BIGINT NOT NULL, ExpectedHours DECIMAL(9,2) NOT NULL DEFAULT 0, AttendanceHours DECIMAL(9,2) NOT NULL DEFAULT 0, RegularHours DECIMAL(9,2) NOT NULL DEFAULT 0, OvtHours DECIMAL(9,2) NOT NULL DEFAULT 0, NightHours DECIMAL(9,2) NOT NULL DEFAULT 0, UnallocatedHours DECIMAL(9,2) NOT NULL DEFAULT 0, OverbookedHours DECIMAL(9,2) NOT NULL DEFAULT 0, ReconciliationStatus NVARCHAR(30) NOT NULL);
GO

IF OBJECT_ID('dbo.TS_ProjectAllocation','U') IS NULL
CREATE TABLE dbo.TS_ProjectAllocation(AllocationId BIGINT IDENTITY PRIMARY KEY, EmployeeDayId BIGINT NOT NULL, ProjectCode NVARCHAR(40) NOT NULL, ActivityCode NVARCHAR(40) NULL, CostCentreCode NVARCHAR(40) NULL, RegularHours DECIMAL(9,2) NOT NULL DEFAULT 0, OvtHours DECIMAL(9,2) NOT NULL DEFAULT 0, NightHours DECIMAL(9,2) NOT NULL DEFAULT 0, WorkLocationCode NVARCHAR(40) NULL, CalendarType NVARCHAR(30) NOT NULL, Comments NVARCHAR(500) NULL);
GO

IF OBJECT_ID('dbo.TS_NightSession','U') IS NULL
CREATE TABLE dbo.TS_NightSession(NightSessionId BIGINT IDENTITY PRIMARY KEY, EmployeeDayId BIGINT NOT NULL, ProjectCode NVARCHAR(40) NOT NULL, SessionStart DATETIME2 NOT NULL, ExpectedEnd DATETIME2 NULL, ActualEnd DATETIME2 NULL, AllowanceAmount DECIMAL(18,2) NOT NULL DEFAULT 1500, AllowanceEligible BIT NOT NULL DEFAULT 0, AuthorizationRef NVARCHAR(80) NULL, Status NVARCHAR(30) NOT NULL);
GO

IF OBJECT_ID('dbo.TS_AttendanceEvidence','U') IS NULL
CREATE TABLE dbo.TS_AttendanceEvidence(AttendanceEvidenceId BIGINT IDENTITY PRIMARY KEY, EmployeeDayId BIGINT NOT NULL, EvidenceType NVARCHAR(50) NOT NULL, ClockIn DATETIME2 NULL, ClockOut DATETIME2 NULL, RawPunchInId BIGINT NULL, RawPunchOutId BIGINT NULL, ResolutionStatus NVARCHAR(40) NOT NULL, ApprovedBy NVARCHAR(80) NULL, ApprovalReason NVARCHAR(500) NULL);
GO

IF OBJECT_ID('dbo.TS_Exception','U') IS NULL
CREATE TABLE dbo.TS_Exception(ExceptionId BIGINT IDENTITY PRIMARY KEY, TimesheetHeaderId BIGINT NULL, EmployeeDayId BIGINT NULL, ExceptionCode NVARCHAR(60) NOT NULL, Severity NVARCHAR(20) NOT NULL, Description NVARCHAR(800) NOT NULL, Status NVARCHAR(20) NOT NULL, ResolvedBy NVARCHAR(80) NULL, ResolvedAt DATETIME2 NULL, Resolution NVARCHAR(800) NULL);
GO

IF OBJECT_ID('dbo.TS_Approval','U') IS NULL
CREATE TABLE dbo.TS_Approval(ApprovalId BIGINT IDENTITY PRIMARY KEY, TimesheetHeaderId BIGINT NOT NULL, AllocationId BIGINT NULL, Stage NVARCHAR(40) NOT NULL, ApproverScope NVARCHAR(80) NULL, ApproverUserId NVARCHAR(80) NULL, Status NVARCHAR(30) NOT NULL, ActionAt DATETIME2 NULL, Comments NVARCHAR(800) NULL);
GO

IF OBJECT_ID('dbo.TS_Audit','U') IS NULL
CREATE TABLE dbo.TS_Audit(AuditId BIGINT IDENTITY PRIMARY KEY, EntityType NVARCHAR(50) NOT NULL, EntityId NVARCHAR(80) NOT NULL, Action NVARCHAR(50) NOT NULL, OldValue NVARCHAR(MAX) NULL, NewValue NVARCHAR(MAX) NULL, Reason NVARCHAR(800) NULL, UserId NVARCHAR(80) NOT NULL, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
GO

IF OBJECT_ID('dbo.TS_PayrollSnapshot','U') IS NULL
CREATE TABLE dbo.TS_PayrollSnapshot(SnapshotId BIGINT IDENTITY PRIMARY KEY, TimesheetPeriodId BIGINT NOT NULL, SnapshotRef NVARCHAR(80) NOT NULL UNIQUE, ReportVersion NVARCHAR(30) NOT NULL, CreatedBy NVARCHAR(80) NOT NULL, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), SnapshotHash NVARCHAR(128) NULL, Status NVARCHAR(20) NOT NULL);
GO

IF OBJECT_ID('dbo.TS_Adjustment','U') IS NULL
CREATE TABLE dbo.TS_Adjustment(AdjustmentId BIGINT IDENTITY PRIMARY KEY, SnapshotId BIGINT NOT NULL, PermanentPersonId UNIQUEIDENTIFIER NOT NULL, WorkDate DATE NOT NULL, OriginalJson NVARCHAR(MAX) NOT NULL, CorrectedJson NVARCHAR(MAX) NOT NULL, Reason NVARCHAR(800) NOT NULL, RequestedBy NVARCHAR(80) NOT NULL, RequestedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), Status NVARCHAR(30) NOT NULL);
GO

CREATE OR ALTER VIEW dbo.vw_TS_BookingSummary AS
SELECT h.TimesheetPeriodId,h.WorkDate,d.PermanentPersonId,SUM(d.RegularHours) RegularHours,SUM(d.OvtHours) OvtHours,SUM(d.NightHours) NightHours,SUM(d.RegularHours+d.OvtHours+d.NightHours) TotalHours
FROM dbo.TS_Header h JOIN dbo.TS_EmployeeDay d ON d.TimesheetHeaderId=h.TimesheetHeaderId GROUP BY h.TimesheetPeriodId,h.WorkDate,d.PermanentPersonId;
GO
