import React,{useMemo,useState}from'react';
import{Badge,Button,Tabs}from'../components/UI';

const TABS=['Crew Assignment','Reassignment & Transfer','Temporary Deployment','Operational Status','Assignment History','Removal Requests'];
const people=[
 ['C0231','Ibrahim Musa','Contract','Mechanical','Unassigned','—','AGEGE'],['C0456','Helen Okeke','Contract','Fabrication','Temporarily Deployed','0044 - Mr David Ogudu','AGEGE'],['C0612','Tunde Salami','Permanent','Operations','Offshore','MOB-2026-0048','IDI_ORO'],['C0641','Ayo Martins','Permanent','Fabrication','On Approved Leave','—','AGEGE'],['C0714','Daniel Esin','Contract','Maintenance','Unassigned','—','AGEGE'],['C0833','Paul Nwankwo','Permanent','Fabrication','Unassigned','—','AGEGE'],['C0901','Chinedu Eze','Contract','Operations','Assigned (Different)','0027 - Mr Adebowale','IDI_ORO'],['C0915','Babatunde Ali','Permanent','Fabrication','Unassigned','—','AGEGE'],['C0944','Kingsley Udom','Contract','Mechanical','Unassigned','—','AGEGE'],['C1003','Fatima Bello','Permanent','Fabrication','Unassigned','—','AGEGE'],['C1042','Amaka Obi','Contract','Welding','Unassigned','—','AGEGE'],['C1068','Joseph Ekanem','Permanent','Mechanical','Unassigned','—','AGEGE']
].map(([id,name,type,dept,status,current,location])=>({id,name,type,dept,status,current,location}));
const assigned=[
 ['C0001','John Adeleke','Permanent','Fabrication','01/01/2026'],['C0054','Musa Ibrahim','Contract','Fabrication','12/03/2026'],['C0088','Kingsley Okoro','Permanent','Welding','05/02/2026'],['C0112','David Eze','Contract','Fabrication','10/01/2026'],['C0146','Samuel Aina','Permanent','Mechanical','01/01/2026'],['C0173','Peter Obasi','Contract','Fabrication','14/04/2026'],['C0199','Emmanuel Johnson','Permanent','Fabrication','01/01/2026'],['C0215','Henry Etim','Contract','Welding','01/03/2026'],['C0278','Seyi Adeyemi','Permanent','Fabrication','01/01/2026'],['C0301','Victor Danladi','Contract','Mechanical','15/06/2026']
].map(([id,name,type,dept,from])=>({id,name,type,dept,from,status:'Active'}));
const tone=s=>s==='Unassigned'?'slate':s==='Temporarily Deployed'?'blue':s==='Offshore'?'blue':s==='On Approved Leave'?'amber':s==='Assigned (Different)'?'purple':'green';
function SearchCombo({value,setValue,items,placeholder}){const[open,setOpen]=useState(false);const[q,setQ]=useState('');const filtered=items.filter(x=>x.toLowerCase().includes(q.toLowerCase()));return <div className="crewCombo"><button type="button" onClick={()=>setOpen(!open)}><span>{value||placeholder}</span><span>⌄</span></button>{open&&<div className="crewComboMenu"><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder={'Search '+placeholder.toLowerCase()+'...'}/>{filtered.map(x=><button key={x} onClick={()=>{setValue(x);setOpen(false);setQ('')}}>{x}</button>)}</div>}</div>}
export default function CrewAssignments(){
 const[tab,setTab]=useState(TABS[0]);const[selected,setSelected]=useState([]);const[crewSelected,setCrewSelected]=useState([]);const[q,setQ]=useState('');const[location,setLocation]=useState('AGEGE - Agege Yard');const[workCentre,setWorkCentre]=useState('Fabrication');const[supervisor,setSupervisor]=useState('0013 - Mr. Karomwi');const[dept,setDept]=useState('All departments');const[type,setType]=useState('All types');const[status,setStatus]=useState('Unassigned & Available');const[notice,setNotice]=useState('');
 const visible=useMemo(()=>people.filter(p=>`${p.id} ${p.name} ${p.dept}`.toLowerCase().includes(q.toLowerCase())),[q]);
 const toggle=(id,list,setList)=>setList(list.includes(id)?list.filter(x=>x!==id):[...list,id]);
 const assign=()=>{if(!selected.length)return;setNotice(`${selected.length} employee${selected.length>1?'s':''} queued for assignment to ${supervisor}.`);setSelected([]);setTimeout(()=>setNotice(''),3200)};
 return <div className="crewPage"><div className="pageTitle crewTitle"><div><span className="eyebrow">TIMESHEET MANAGEMENT</span><h1>Crew & Assignments</h1><p>Manage home supervisor, location and work centre assignments. Project hours are recorded in Timesheet Entry.</p></div></div>
 <Tabs items={TABS} active={tab} setActive={setTab}/>
 {tab!=='Crew Assignment'?<section className="panel feature"><h3>{tab}</h3><p>This workspace uses effective-dated employee assignment records and preserves full history.</p></section>:<>
 <section className="crewFilters"><div className="crewFilter"><label>Effective Date <b>*</b></label><div className="dateBox"><span>▣</span><input type="date" defaultValue="2026-09-17"/></div></div><div className="crewFilter"><label>Location / Site <b>*</b></label><SearchCombo value={location} setValue={setLocation} items={['AGEGE - Agege Yard','IDI_ORO - Idi-Oro Yard','Nigerian Naval Dockyard','Offshore']} placeholder="Location"/></div><div className="crewFilter"><label>Work Centre <b>*</b></label><SearchCombo value={workCentre} setValue={setWorkCentre} items={['Fabrication','Mechanical','Welding','Production','Maintenance','Operations']} placeholder="Work centre"/></div><div className="crewFilter"><label>Supervisor <b>*</b></label><SearchCombo value={supervisor} setValue={setSupervisor} items={['0013 - Mr. Karomwi','0027 - Mr. Adebowale','0044 - Mr. David Ogudu','C1882 - Mohammed']} placeholder="Supervisor"/></div>
 <div className="crewSearchBox">⌕ <input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search employee code or name..."/></div><div className="crewFilter"><label>Department</label><SearchCombo value={dept} setValue={setDept} items={['All departments','Fabrication','Mechanical','Welding','Operations','Maintenance']} placeholder="Department"/></div><div className="crewFilter"><label>Employee Type</label><SearchCombo value={type} setValue={setType} items={['All types','Permanent','Contract','Daily Rate']} placeholder="Employee type"/></div><div className="crewFilter"><label>Status</label><SearchCombo value={status} setValue={setStatus} items={['Unassigned & Available','All statuses','Temporarily Deployed','Offshore','On Approved Leave','Assigned (Different)']} placeholder="Status"/></div><button className="resetBtn">↻ &nbsp; Reset Filters</button></section>
 <section className="crewInfo"><div className="crewInfoText"><span className="infoDot">i</span><div><b>Assign employees to the selected supervisor to set their home supervisor, location and work centre.</b><small>This does not create project hours. Project hours are recorded in Timesheet Entry.</small></div></div><div className="crewStat"><b>♧ &nbsp;12</b><span>Available (Filtered)</span></div><div className="crewStat orange"><b>♧ &nbsp;28</b><span>Currently Assigned</span></div><div className="crewStat green"><b>▣ &nbsp;40</b><span>Total Crew (Location + Work Centre)</span></div></section>
 {notice&&<div className="success">{notice}</div>}
 <section className="crewDual"><div className="crewCard"><div className="crewCardHead"><div><h3>Available Employees</h3><p>Employees who can be assigned to the selected supervisor.</p></div><div><b>{visible.length} employees</b><label><input type="checkbox" checked={visible.length>0&&visible.every(x=>selected.includes(x.id))} onChange={()=>setSelected(visible.every(x=>selected.includes(x.id))?[]:visible.map(x=>x.id))}/> Select All</label></div></div><div className="crewTableWrap"><table className="crewTable"><thead><tr><th></th><th>Code</th><th>Employee Name</th><th>Type</th><th>Department</th><th>Status</th><th>Current Supervisor</th></tr></thead><tbody>{visible.map(p=><tr key={p.id}><td><input type="checkbox" checked={selected.includes(p.id)} onChange={()=>toggle(p.id,selected,setSelected)}/></td><td>{p.id}</td><td>{p.name}</td><td>{p.type}</td><td>{p.dept}</td><td><Badge tone={tone(p.status)}>{p.status}</Badge></td><td>{p.current}</td></tr>)}</tbody></table></div><div className="crewPager"><span>Showing 1 to {Math.min(10,visible.length)} of {visible.length} employees</span><div><button>‹</button><button className="on">1</button><button>2</button><button>›</button><select><option>10 / page</option><option>25 / page</option></select></div></div></div>
 <div className="crewTransfer"><button className="assignArrow" disabled={!selected.length} onClick={assign}>»<span>Assign<br/>Selected ({selected.length})</span></button><button className="removeArrow" disabled={!crewSelected.length}>«<span>Remove<br/>Selected ({crewSelected.length})</span></button></div>
 <div className="crewCard"><div className="crewCardHead"><div><h3>Assigned Crew</h3><p>Employees currently assigned to {supervisor}.</p></div><div><b>28 employees</b><label><input type="checkbox" checked={assigned.every(x=>crewSelected.includes(x.id))} onChange={()=>setCrewSelected(assigned.every(x=>crewSelected.includes(x.id))?[]:assigned.map(x=>x.id))}/> Select All</label></div></div><div className="crewTableWrap"><table className="crewTable"><thead><tr><th></th><th>Code</th><th>Employee Name</th><th>Type</th><th>Department</th><th>Assigned From</th><th>Status</th><th>Actions</th></tr></thead><tbody>{assigned.map(p=><tr key={p.id}><td><input type="checkbox" checked={crewSelected.includes(p.id)} onChange={()=>toggle(p.id,crewSelected,setCrewSelected)}/></td><td>{p.id}</td><td>{p.name}</td><td>{p.type}</td><td>{p.dept}</td><td>{p.from}</td><td><Badge tone="green">Active</Badge></td><td><button className="kebab">⋮</button></td></tr>)}</tbody></table></div><div className="crewPager"><span>Showing 1 to 10 of 28 employees</span><div><button>‹</button><button className="on">1</button><button>2</button><button>3</button><button>›</button><select><option>10 / page</option></select></div></div></div></section>
 <div className="crewBottom"><Button kind="secondary">▧ &nbsp; Request Removal</Button><Button onClick={assign}>▣ &nbsp; Save Assignments</Button></div></>}</div>}
