import React,{useState}from'react';import{employees}from'../data/mock';import{Badge,Button,Field,Modal,Tabs,Table}from'../components/UI';
const C={
'Crew & Assignments':['Supervisor Assignments','Temporary Assignments','Operational Status','Assignment History'],
'Attendance Reconciliation':['Daily Reconciliation','Biometric Punches','Identity Mapping','Manual Attendance','Exceptions'],
'OVT & Night Work':['OVT','Night Work','Authorizations','Exceptions'],
'Offshore & Mobilization':['Mobilized Crew','New Mobilization','Demobilization','Returning Crew','History','Exceptions'],
'Approvals':['Supervisor','Cost Control','Project Manager','Consolidation','HR','Payroll Readiness'],
'Corrections & Adjustments':['Draft Corrections','Returned','Recall Requests','Post-Approval Adjustments','History'],
'Configuration':['Work Calendar','Public Holidays','Shifts','Locations','OVT Rules','Night Work Rules','Internal Activities','Submission Rules','Approval Rules','Exception Rules','Biometric Mapping']};
const desc={'Crew & Assignments':'Effective-dated crew, supervisor and temporary operational assignments.','Attendance Reconciliation':'Resolve attendance evidence while preserving immutable raw biometric punches.','OVT & Night Work':'Control project overtime, night sessions, authorizations and allowance eligibility.','Offshore & Mobilization':'Manage offshore deployment without automatically creating attendance or hours.','Approvals':'Role-scoped approval queues from Supervisor through Payroll Readiness.','Corrections & Adjustments':'Controlled correction mechanisms based on workflow and payroll state.','Configuration':'Central business-rule configuration with effective dates and audit history.'};
export default function Workspace({type}){const tabs=C[type], [tab,setTab]=useState(tabs[0]),[modal,setModal]=useState(false);return <><div className="pageTitle"><div><span className="eyebrow">{type.toUpperCase()}</span><h1>{type}</h1><p>{desc[type]}</p></div><Button onClick={()=>setModal(true)}>+ New Action</Button></div><Tabs items={tabs} active={tab} setActive={setTab}/><div className="panel"><div className="panelHead"><div><h3>{tab}</h3><p>Role-based access · effective dating · complete audit history</p></div><div className="actions"><input className="searchInput" placeholder="Search..."/><Button kind="secondary">Export</Button></div></div>{type==='Configuration'?<Config tab={tab}/>:<Operational type={type} tab={tab}/>}</div>{modal&&<ActionModal type={type} tab={tab} close={()=>setModal(false)}/>}</>}
function Operational({type,tab}){let heads=['Employee','Supervisor','Location','Project / Context','Effective / Hours','Status','Action'];let rows=employees.slice(0,10).map((e,i)=>[e.id+' · '+e.name,e.supervisor,e.location,e.project,type==='Approvals'?(e.reg+e.ovt)+'h':'25 Sep 2026',<Badge tone={i%4?'green':'amber'}>{type==='Approvals'?(i%4?'Pending':'Exception'):(i%4?'Active':'Review')}</Badge>,<button className="link">Open</button>]);return <><div className="filterRow"><Field label="Period"><select><option>September 2026</option></select></Field><Field label="Supervisor"><select><option>All Supervisors</option></select></Field><Field label="Location"><select><option>All Locations</option></select></Field><Field label="Status"><select><option>All Statuses</option></select></Field></div><Table headers={heads} rows={rows}/></>}
function Config({tab}){let rules=[['Normal Day Shift','07:30 – 16:30','1 hour break · 8 standard hours'],['Night Work Start','18:00','Cross-midnight session enabled'],['Night Allowance','₦1,500','Per eligible approved session'],['Draft Reminder','Next working day','Escalation enabled'],['Period Close Control','Completeness required','Override requires reason + authorization'],['Public Holiday Source','Official Calendar','Effective by company/location/year']];return <div className="ruleGrid">{rules.map(r=><div><span>{tab}</span><b>{r[0]}</b><strong>{r[1]}</strong><p>{r[2]}</p><button>Edit rule</button></div>)}</div>}
function ActionModal({type,tab,close}){return <Modal title={'New '+tab} onClose={close} footer={<><Button kind="secondary" onClick={close}>Cancel</Button><Button onClick={close}>Save & Validate</Button></>}><div className="formGrid"><Field label="Employee / Crew"><select><option>Select employee or crew...</option></select></Field><Field label="Effective Date"><input type="date" defaultValue="2026-09-25"/></Field><Field label="Project / Context"><input placeholder="Project, assignment or reference"/></Field><Field label="Reason / Authorization"><input placeholder="Required business reason"/></Field><Field label="Notes"><textarea placeholder="Comments and supporting information"/></Field></div><div className="infoBox">This action is audit-controlled. Existing historical records will not be overwritten.</div></Modal>}
